name: CI Pipeline

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:


#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  maven-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 20
      uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

#    - name: Submit Dependency Snapshot
#      uses: advanced-security/maven-dependency-submission-action@v4

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: hello-world-docker
        path: target/*.jar

  docker-build-and-publish:
    needs: maven-build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: hello-world-docker
        path: target/

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag aberner/microsave:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Push Docker image to Docker Hub
      run: docker push aberner/microsave:latest

  deploy-to-azure-test:
    needs: docker-build-and-publish
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: microsave-test-app-service
        slot-name: production
        images: aberner/microsave:latest


  deploy-to-azure-prod:
    needs: deploy-to-azure-test
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}      

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: microsave-prod-app-service
        slot-name: production
        images: aberner/microsave:latest
