name: Java CI with Checkstyle and SpotBugs

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step to check out the repository
    - name: Check out the repository
      uses: actions/checkout@v2

    # Step to set up JDK 11
    - name: Set up JDK 20
      uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven

    # Step to build the project with Maven
    - name: Build with Maven
      run: mvn clean install

  checkstyle:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Step to run Checkstyle
    - name: Run Checkstyle
      run: mvn checkstyle:check
  spotbugs:
    # Step to run SpotBugs
    - name: Run SpotBugs
      run: mvn spotbugs:check
