name: Java CI with Checkstyle and SpotBugs

on: [push, pull_request]
workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step to check out the repository
    - name: Check out the repository
      uses: actions/checkout@v2

    # Step to set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    # Step to build the project with Maven
    - name: Build with Maven
      run: mvn clean install

  checkstyle:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Step to check out the repository
    - name: Check out the repository
      uses: actions/checkout@v2

    # Step to set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    # Step to run Checkstyle
    - name: Run Checkstyle
      run: mvn checkstyle:check

    # Step to upload Checkstyle report
    - name: Upload Checkstyle Report
      uses: actions/upload-artifact@v2
      with:
        name: checkstyle-report
        path: target/checkstyle-result.xml

  spotbugs:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Step to check out the repository
    - name: Check out the repository
      uses: actions/checkout@v2

    # Step to set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    # Step to run SpotBugs
    - name: Run SpotBugs
      run: mvn spotbugs:check

    # Step to upload SpotBugs report
    - name: Upload SpotBugs Report
      uses: actions/upload-artifact@v2
      with:
        name: spotbugs-report
        path: target/spotbugsXml.xml