name: Java CI with Checkstyle and SpotBugs

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up JDK 20
      uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

  checkstyle:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up JDK 20
      uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven

    - name: Run Checkstyle
      run: mvn checkstyle:check
      working-directory: ${{ github.workspace }}
    - name: Parse Checkstyle Errors
      if: failure()
      run: |
        echo "Checkstyle errors summary:"
        grep -oP '\(\K[^\)]*' target/checkstyle-result.xml
      shell: bash
  spotbugs:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up JDK 20
      uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven

    - name: Run SpotBugs
      run: mvn spotbugs:check